{% set name = "fiftyone-brain" %}
{% set version = "0.21.2" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 73c719ac509b0e074c450efa513478332c506cc747ed69a3568edd96c46f6164

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy >=1.2.0
    - scikit-learn

test:
  imports:
    # - fiftyone.brain # would create a cyclic dependency
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/fiftyone-brain/
  summary: FiftyOne Brain
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lucasew
