{% set name = "fiftyone-brain" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fiftyone-brain-{{ version }}.tar.gz
  sha256: a3f52bf5b7be1516f7b5202b434d8e15cf60e570b1b9d13652a0ad9610864b67

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy >=1.2.0
    - scikit-learn

test:
  imports:
    # - fiftyone.brain # would create a cyclic dependency
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/fiftyone-brain/
  summary: FiftyOne Brain
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lucasew
